backend/controllers/CompanyController.php
<?php

namespace backend\controllers;

use common\entities\Admin;
use common\entities\Document;
use Yii;
use common\entities\Company;
use common\entities\search\CompanySearch;
use yii\db\StaleObjectException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends Controller {
    /**
     * {@inheritdoc}
     */
    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @return mixed
     */
    public function actionIndex(){
        $searchModel = new CompanySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Company model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id){
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Company model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate(){
        $model = new Company();

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Company model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->renderAjax('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Company model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete(int $id){
        $user = Admin::findOne(Yii::$app->user->identity->getId());
        $company = $this->findModel($id);

        if($user->role->id == 1){
            $q = Document::find()->where(['company_id' => $company->id])->count();
            if($q < 1){
                $company->delete();
                Yii::$app->session->setFlash("info", "Usunięto - " . $company->name);
            }
            else{
                Yii::$app->session->setFlash("danger", "Uwaga! nie można usunąć " . $company->name . " ta firma ma podpisane umowy");
            }
        }
        else  Yii::$app->session->setFlash("danger", "Brak uprawień");

        return $this->redirect(['index']);
    }

    /**
     * Finds the Company model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Company the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id){
        if(($model = Company::findOne($id)) !== null){
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/controllers/DocumentController.php
<?php

namespace backend\controllers;

use common\entities\Admin;
use common\entities\File;
use common\entities\Helper;
use common\statuses\MyStatus;
use Worker;
use Yii;
use common\entities\Document;
use common\entities\search\DocumentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

/**
 * DocumentController implements the CRUD actions for Document model.
 */
class DocumentController extends Controller {
    public function beforeAction($action){

        $this->enableCsrfValidation = false;

        if(in_array($action->id, ['index'])){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function behaviors(){
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Document models.
     * @return mixed
     */
    public function actionIndex(){
        $worker_id = Yii::$app->user->identity->getId();
        $worker = Admin::findOne($worker_id);
        $allowedCategories = $worker->getAllowedCategories();
        $allowedTypes = $worker->getAllowedTypes();
        $searchModel = new DocumentSearch($allowedCategories, $allowedTypes);
        if($a = Yii::$app->request->get('DocumentSearch') ?? false){
            $searchModel->company_name = $a['company_name'];
            $searchModel->company_acronim = $a['company_acronim'];
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Document model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id){
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Document model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate(){
        $model = new Document();
        $model->number = Helper::generateNumber();
        $model->created_admin_id = Yii::$app->user->getId();

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            $model->imageFile = UploadedFile::getInstances($model, 'imageFile');
            if(!empty($model->imageFile)){
                $model->scenario = 'fileUploaded';
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if($model->load(Yii::$app->request->post())){
            $tmp = $model->imageFile = UploadedFile::getInstances($model, 'imageFile');
            if(!empty($model->imageFile)){
                $model->scenario = 'fileUploaded';
            }

            if(!$model->date_end_str){
                $model->date_end_str = '2045-06-10';
                // $model->date_end = 2147483647;
            }
            if($model->save()){
                Helper::confirmNumber();
                $model->imageFile = $tmp;
                if($model->upload()){
                    Yii::$app->session->setFlash('info', "Wszystko ok");
                }
            }


            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Document model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            $model->imageFile = UploadedFile::getInstances($model, 'imageFile');
            if(!empty($model->imageFile)){
                $model->scenario = 'fileUploaded';
            }
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }


        if($model->load(Yii::$app->request->post())){
            if(!$model->date_end_str){
                $model->date_end_str = '2045-06-10';
                // $model->date_end = 2147483647;
            }
            $tmp = $model->imageFile = UploadedFile::getInstances($model, 'imageFile');
            if(!empty($model->imageFile)){
                $model->scenario = 'fileUploaded';
            }
            $model->save();
            $model->imageFile = $tmp;
            if($model->upload()){
                Yii::$app->session->setFlash('info', "Wszystko ok");
            }
            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->renderAjax('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Document model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id){

        $user = Admin::findOne(Yii::$app->user->identity->getId());
        if($user->role->id == 1){
            $files = File::find()->where(['document_id' => $id])->all();
            try {
                foreach($files as $file){
                    unlink('uploads/' . $file->hash);
                    $file->delete();
                }
            } catch(\Exception $e){
                Yii::$app->session->setFlash("danger", "Brak możliwości usunięcia pliku, zgloś to administratorowi");
            }
            $this->findModel($id)->delete();
            Yii::$app->session->setFlash('info', 'Dokument usunięto');
        }
        else  Yii::$app->session->setFlash("danger", "Brak uprawień");

        return $this->redirect(['index']);
    }

    public function actionRemoveFile($document_id, $hash){
        if(Yii::$app->user->identity){
            $file = File::find()->where(['hash' => $hash])->one();
            if($file && $file->document_id == $document_id){

                $file->delete();
                unlink('uploads/' . $hash);
                Yii::$app->session->setFlash('info', "Plik $file->name z dokumentu skutećno wydaleno");

            }
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionClose($document_id){
        $document = $this->findModel($document_id);
        $document->status = MyStatus::STATUS_INACTIVE;
        $document->save();
        Yii::$app->session->setFlash("info", "Umowa " . $document->number . 'zakończona i  wyslana do archiwum');
        return $this->redirect(['index']);
    }

    public function actionActivate($document_id){
        $document = $this->findModel($document_id);
        $document->status = MyStatus::STATUS_ACTIVE;
        $document->save();
        Yii::$app->session->setFlash("info", "Umowa " . $document->number . 'aktywowana');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Document model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Document the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id){
        if(($model = Document::findOne($id)) !== null){
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/document/_form.php
<?php

use common\entities\File;
use common\entities\Helper;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\entities\Document */
/* @var $form yii\widgets\ActiveForm */

$categories = \common\entities\Category::getSimpleFilter();
$types = \common\entities\Type::getSimpleFilter();
$periods = \common\entities\Period::getSimpleFilter();

?>

    <div id="form" class="document-form">

        <?php $form = ActiveForm::begin([
            'id'      => 'document-form',
            //'enableAjaxValidation' => true,
            'options' => ['enctype' => 'multipart/form-data'],
        ]); ?>

        <div class="row">
            <div class="col-sm-6">

                <?= $form->field($model, 'company_id')
                    ->textInput()
                    ->dropDownList(\yii\helpers\ArrayHelper::map(\common\entities\Company::find()->all(), 'id', 'name'),
                        [
                            'class'  => 'chosen-select form-control',
                            'prompt' => 'Wyszukaj firmę',
                        ])
                    ->label('Nazwa firmy')

                ?>


            </div>
            <div class="col-sm-6">

                <?= Html::a('Nie ma firmy? Dodaj firmę', '/company/create', ['class' => 'btn btn-primary my-modal-md', 'style' => 'margin-top:22px']) ?>
            </div>
        </div>


        <?php // $form->field($model, 'name')->textInput(['maxlength' => true])->label('Nazwa umowy') ?>

        <?= $form->field($model, 'category_id')->textInput()->dropDownList($categories, ['prompt' => '-- BRAK --'])->label('Nazwa kategorii') ?>
        <?= $form->field($model, 'type_id')->textInput()->dropDownList($types, ['prompt' => '-- BRAK --'])->label('Typ kontrahenta') ?>
        <?= $form->field($model, 'period_id')->textInput()->dropDownList($periods, ['prompt' => '-- BRAK --'])->label('Okres wypowiedzenia') ?>
        <?= $form->field($model, 'admin_id')
            ->textInput()
            ->dropDownList(\common\entities\Admin::getAllUser(), [
                'class'  => 'chosen-select',
                'prompt' => '-- BRAK --'])
            ->label('Opiekun')
        ?>
        <?= $form->field($model, 'date_init_str')->widget(DatePicker::className(), [
            'name'          => 'dp_1',
            'type'          => DatePicker::TYPE_INPUT,
            'options'       => ['placeholder' => 'Data zawarcia umowy/aneksu'],
            'convertFormat' => true,
            'pluginOptions' => [
                'format'    => 'yyyy-MM-dd',
                'autoclose' => true,
                'weekStart' => 1, //неделя начинается с понедельника
                'startDate' => '01.05.2018', //самая ранняя возможная дата
                'todayBtn'  => false, //снизу кнопка "сегодня"
                'style'     => 'color:red',
            ],
        ])->label('Data zawarcia umowy/aneksu'); ?>
        <?= $form->field($model, 'date_start_str')->widget(DatePicker::className(), [
            'name'          => 'dp_2',
            'type'          => DatePicker::TYPE_INPUT,
            'options'       => ['placeholder' => 'Umowa rozpoczięta'],
            'convertFormat' => true,
            //'value' => date("d.m.Y", (integer)$model->date_end),
            'pluginOptions' => [
                'format'    => 'yyyy-MM-dd',
                'autoclose' => true,
                'weekStart' => 1, //неделя начинается с понедельника
                'startDate' => '01.05.2018', //самая ранняя возможная дата
                'todayBtn'  => false, //снизу кнопка "сегодня"
            ],
        ])->label('Data rozpoczęcia umowy'); ?>
        <div id="radio">
            <p>Czas trwania umowy:</p>

            <div>
                <input type="radio" id="time-nieok" name="radio" value="10">
                <label for="dewey">Nieokreślony</label>
            </div>

            <div>
                <input type="radio" id="time-ok" name="radio" value="0" checked>
                <label for="huey">Określony</label>
            </div>
        </div>
        <div id="period">
            <?= $form->field($model, 'date_end_str')->widget(DatePicker::className(), [
                'name'          => 'dp_3',
                'type'          => DatePicker::TYPE_INPUT,
                'options'       => ['placeholder' => 'Data zakończenia umowy'],
                'convertFormat' => true,
                //'value' => date("d.m.Y", (integer)$model->time_payment_str),
                'pluginOptions' => [
                    'format'    => 'yyyy-MM-dd',
                    'autoclose' => true,
                    'weekStart' => 1, //неделя начинается с понедельника
                    'startDate' => '01.05.2018', //самая ранняя возможная дата
                    'todayBtn'  => false, //снизу кнопка "сегодня"
                ],
            ])->label('Data zakończenia umowy'); ?>
        </div>
        <?= $form->field($model, 'description')->textarea(['rows' => 5])->label('Przedmiot umowy') ?>
        <?= $form->field($model, 'imageFile[]')
            ->fileInput(['multiple' => true])
            ->label('Dodaj nowe pliki') ?>
        <?php

        if($model->id > 1){
            $files = File::find()->where(['document_id' => $model->id])->all();
            $a = '';
            foreach($files as $file){
                $a .= "<a target='_blank' 
                                  href='/uploads/$file->hash' 
                                  download='$file->name'>$file->name$file->extension</a> 
                                    - 
                               <a target='_blank' href='/document/remove-file/$file->document_id/$file->hash'> usuń </a>
                               
                               <br>";
            }
            echo $a;
        }

        ?>

        <div class="form-group" style="text-align: right">

            <?= Html::a('Usuń', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'style' => 'margin-right:100px',
                'data'  => [
                    'confirm' => 'Naprawde chcesz usunąć ten document?',
                    'method'  => 'post',
                ],
            ]) ?>


            <?= Html::submitButton('Zapisz', ['class' => 'btn btn-success mybtn']) ?>
        </div>


        <?php ActiveForm::end(); ?>

    </div>
    <div>

        <div id="spinner" class="sk-spinner sk-spinner-fading-circle hide" style="width: 150px; height: 150px;">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>

    </div>


<?php
$this->registerJs('$(".chosen-select").chosen({width: "100%"});

$(".mybtn").click(function (){
    $("#form").addClass(\'hide\');
    $("#spinner").removeClass(\'hide\');
});

')
?>

backend/views/document/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\entities\search\DocumentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="document-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date_start') ?>

    <?= $form->field($model, 'date_end') ?>

    <?= $form->field($model, 'time_payment') ?>

    <?= $form->field($model, 'time_delivery') ?>

    <?php // echo $form->field($model, 'files') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'company_id') ?>

    <?php // echo $form->field($model, 'name') ?>

    <?php // echo $form->field($model, 'number') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/document/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\entities\Document */

$this->title = 'Rejestracja nowej umowy Nr' . $model->number;

?>
<div class="document-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/document/index.php
<?php

use common\entities\Company;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\entities\search\DocumentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Umowy';
//$this->params['breadcrumbs'][] = $this->title;

$companiesFilter = Company::getSimpleFilter();
$acronimFilter = Company::getAllAcronims();

$this->params['url'] = 'advances_form';

$category = \common\entities\Category::getSimpleFilter();
$types = \common\entities\Type::getSimpleFilter();


?>
    <div class="document-index">

        <p>
            <?= Html::a('Dodaj nową umowe', ['create'], ['class' => 'btn  btn-sm btn-success my-modal-md']) ?>
            <?php echo Html::a('Usuń filtry', '/document', ['class' => 'btn btn-sm btn-info']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel'  => $searchModel,
            'options'      => ['style' => 'table-layout:fixed; width:1300px'],

            'rowOptions' => function($model, $key, $index, $grid){


                $marker = '';

                if($model->date_end - (2592000 * 3) < time()) $marker = 'background-color: #fcffc7'; // за 3 місяці кінець умови
                if($model->date_end - 2592000 < time()) $marker = 'background-color: #ffc7c7'; // за 30 днів кінець умови
                if($model->status == \common\statuses\MyStatus::STATUS_INACTIVE) $marker = 'background-color: #d4d4d4'; // умова заерита та списана до архіву


                return ['style' => $marker];

            },
            'columns'    => [
                ['class' => 'yii\grid\SerialColumn', 'contentOptions' => ['style' => 'width: 40px;']],
                [
                    'contentOptions' => ['style' => 'width: 80px;'],
                    'label'          => 'Numer umowy',
                    'format'         => 'raw',
                    'attribute'      => 'number',
                    'value'          => function($data){
                        return '<a title="' . $data->description . '">' . $data->number . '</a>';
                    },
                ],

                [
                    'contentOptions' => ['style' => 'width: 100px; '],
                    'label'          => 'Akronim',
                    'format'         => 'raw',
                    'attribute'      => 'company_acronim',
                    'value'          => function($data){
                        return Html::a(
                            $data->company->acronim,
                            '/document/index?DocumentSearch%5Bcompany_id%5D=' . $data->company_id
                        );
                    },
                ],

                [
                    'contentOptions' => ['style' => 'width: 150px;'],
                    'label'          => 'Nazwa firmy',
                    'format'         => 'raw',
                    'attribute'      => 'company_name',
                    'value'          => function($data){
                        return Html::a(
                            $data->company->name,
                            '/document/index?DocumentSearch%5Bcompany_id%5D=' . $data->company_id
                        );
                    },
                ],
                [
                    'contentOptions' => ['style' => 'width: 60px;'],
                    'label'          => 'Kategoria',
                    'format'         => 'raw',
                    'attribute'      => 'category_id',
                    'filter'         => $category,
                    'value'          => function($data){
                        return Html::a(
                            $data->category->name ?? ''
                        );
                    },
                ],
                /*     [
                         'contentOptions' => ['style' => 'width: 100px; max-width: 100px;', ],
                         'label'          => 'Typ kontrahenta',
                         'format'         => 'raw',
                         'attribute'      => 'type_id',
                         'filter'         => $types,
                         'value'          => function($data){
                             return Html::a(
                                 $data->type->name ?? ''
                             );
                         },
                     ],*/


                /*  [
                      'contentOptions' => ['style' => 'width: 200px; max-width: 200px;'],
                      'label'          => 'Nazwa umowy',
                      'format'         => 'raw',
                      'attribute'      => 'name',
                  ],*/
                /*  [
                      'contentOptions' => ['style' => 'width: 110px;'],
                      'label'          => 'Data zawarcia',
                      'format'         => 'raw',
                      'attribute'      => 'date_start_str',
                  ],*/
                [
                    'contentOptions' => ['style' => 'width: 100px;'],
                    'label'          => 'Data zawarcia',
                    'format'         => 'raw',
                    'attribute'      => 'date_init_str',
                ],
                [
                    'contentOptions' => ['style' => 'width: 100px;'],
                    'label'          => 'Data zakończenia',
                    'format'         => 'raw',
                    'attribute'      => 'date_end_str',
                    'value'          => function($data){
                        if($data->date_end == 2147483647){
                            return 'czas nieokreślony';
                        }
                        return $data->date_end_str;
                    },
                ],


                ['contentOptions' => ['style' => 'width: 100px;'],
                 'format'         => 'raw',
                 'value'          => function($data){
                     $url = '/document/view?id=' . $data->id;
                     return Html::a('Podgłąd', $url, ['class' => "my-modal-lg btn btn-info btn-xs",
                                                      'title' => $data->description,
                     ]);
                 },
                ],
            ],
        ]); ?>
    </div>
<?php
$js = <<<'TAG'
$(document).ready(function () { 

    $(document).on('click', '#radio', function (e) {
        
        var value = $('input[name="radio"]:checked').val();
        if(value == 0) {
            $('#period').removeClass('hide');            
        }
        if(value == 10) {
            $('#period').addClass('hide');
            $('#document-date_end_str').val('');
            
        }
     });
});
TAG;
$this->registerJs('$(".chosen-select").chosen({width: "100%"});');
$this->registerJs($js, $this::POS_READY);


?>

backend/views/document/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\entities\Document */

$this->title = 'Edytój umowę: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Documents', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="document-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>